// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

const fibonacci = () => {
  let oldNum = 0
  let newNum = 1
  let sum = 0
  for(let i=0; ;i++) {
    const nextNum = oldNum + newNum
    if(nextNum > 4000000) {
      break
    }
    if(nextNum % 2 === 0){
      sum += nextNum
    }
    oldNum = newNum
    newNum = nextNum
  }
  console.log(sum);
}
